version: '3.8'

services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo_network

  backend:
    build: ./backend
    restart: always
    ports:
      - "8080:5001"  # <--- This tells Flask to show up directly on port 8080!
    environment:
      - DB_HOST=database
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./frontend:/app/frontend  # Allows Flask to see your templates folder
    depends_on:
      - database
    networks:
      - todo_network

volumes:
  postgres_data:

networks:
  todo_network:
